<?php
/**
 * Created by PhpStorm.
 * User: a6y
 * Date: 09.04.18
 * Time: 13:47
 */

use Doggy\PlushLabrador;

class PlushLabradorTest extends AbstractDoggyTest
{
    /**
     * @throws \DI\DependencyException
     * @throws \DI\NotFoundException
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->doggy = $this->container->get(class_basename(PlushLabrador::class));
    }

    public function testGetPriceIsRight()
    {
        $this->assertEquals(200, $this->doggy->getPrice());
    }

    public function testgetPriceIsWrong()
    {
        $this->assertNotEquals(0, $this->doggy->getPrice());
    }
}