<?php
/**
 * Created by PhpStorm.
 * User: a6y
 * Date: 09.04.18
 * Time: 13:54
 */

use Doggy\RubberDachshund;

class RubberDachshundTest extends AbstractDoggyTest
{
    /**
     * @throws \DI\DependencyException
     * @throws \DI\NotFoundException
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->doggy = $this->container->get(class_basename(RubberDachshund::class));
    }

    public function testGetPriceIsRight()
    {
        $this->assertEquals(100, $this->doggy->getPrice());
    }

    public function testGetPriceIsWrong()
    {
        $this->assertNotEquals(-1, $this->doggy->getPrice());
    }

    public function testPeepIsNotEmpty()
    {
        $this->assertNotEmpty($this->doggy->peep());
    }

    public function testPeepIsWrong()
    {
        $this->assertNotEquals("Wrong peep mess", $this->doggy->peep());
    }
}